name: .NET format

on: [push, pull_request]

jobs:
  dotnet-format:
    runs-on: windows-2022
    steps:
      - name: Use CRLF line endings
        run: git config --global core.autocrlf true
           
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore -p:EnableWindowsTargeting=true

      - name: Run dotnet format
        run: dotnet format --verify-no-changes --verbosity diagnostic
